import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, RedirectToSignIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import { auth } from "@clerk/nextjs/server";
import { SelectedSentencesProvider } from "@/contexts/SelectedSentencesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await auth.protect();

  return (
    <ClerkProvider>
      <SelectedSentencesProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} bg-purple-950 antialiased`}>
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
            {children}
          </body>
        </html>
      </SelectedSentencesProvider>
    </ClerkProvider>
  );
}
